/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/is-uninitialized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check if the core server is uninitialized. Return true if there is no user in the database. */
        get: operations["getIs-uninitialized"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postSign-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description NOTE: Currently only allow one user to sign up. */
        post: operations["postSign-up"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getIs-uninitialized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                    "multipart/form-data": boolean;
                    "text/plain": boolean;
                };
            };
        };
    };
    "postSign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
                "multipart/form-data": {
                    username: string;
                    password: string;
                };
                "text/plain": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                    "multipart/form-data": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                    "text/plain": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                };
            };
        };
    };
    "postSign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
                "multipart/form-data": {
                    username: string;
                    password: string;
                };
                "text/plain": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                    "multipart/form-data": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                    "text/plain": {
                        /** @default 0 */
                        code: number;
                        /** @default success */
                        msg: string;
                        data?: {
                            token: string;
                        };
                    };
                };
            };
        };
    };
}
